// Beer data structure
const beers = {
  darkBeers: [
    {
        name: "Karma",
        rating: 3.55,
        ratingCount: "7k",
        untappdUrl: "https://untappd.com/b/hop-nation-brewing-co-karma/2640813",
        imageUrl: "assets/dark beer/Karma.svg",
        price: 5.99,
        bulkPrice: 21.99,
        bundleQuantity: 4,
        ABV: 5,
        size: 355,
      },
      {
        name: "Peanut Butter",
        rating: 3.87,
        ratingCount: "4k",
        untappdUrl: "https://untappd.com/b/bad-shepherd-brewing-co-peanut-butter-porter/3324891",
        imageUrl: "assets/dark beer/Peanut Butter.svg",
        price: 6.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 6.4,
        size: 355,
      },
      {
        name: "Staircase",
        rating: 3.66,
        ratingCount: "1.5k",
        untappdUrl: "https://untappd.com/b/bright-brewery-staircase-porter/38050",
        imageUrl: "assets/dark beer/Staircase.svg",
        price: 6.99,
        bulkPrice: 11.99,
        bundleQuantity: 2,
        ABV: 5.7,
        size: 355,
      },
      {
        name: "Moon Dust",
        rating: 3.86,
        ratingCount: "2.6k",
        untappdUrl: "https://untappd.com/b/mountain-culture-beer-co-moon-dust/3477131",
        imageUrl: "assets/dark beer/Moon Dust.svg",
        price: 6.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 5.6,
        size: 355,
      },
      {
        name: "Hefeweissbier ...",
        rating: 3.76,
        ratingCount: "103k",
        untappdUrl: "https://untappd.com/b/bayerische-staatsbrauerei-weihenstephan-weihenstephaner-hefeweissbier-dunkel/6273",
        imageUrl: "assets/dark beer/Hefeweissbier Dunkel.svg",
        price: 7.99,
        bulkPrice: 20.99,
        bundleQuantity: 3,
        ABV: 5.3,
        size: 500,
      },
      {
        name: "Belgian Mocha...",
        rating: 4.12,
        ratingCount: "1k",
        untappdUrl: "https://untappd.com/b/bacchus-brewing-co-belgian-mocha-stout/157605",
        imageUrl: "assets/dark beer/Belgian Mocha Stout.svg",
        price: 12.99,
        bulkPrice: 23.99,
        bundleQuantity: 2,
        ABV: 7.8,
        size: 375,
      },
      {
        name: "Hyperspatial ...",
        rating: 4.04,
        ratingCount: "3xx",
        untappdUrl: "https://untappd.com/b/bacchus-brewing-co-hyperspatial-espresso-stout/1793124",
        imageUrl: "assets/dark beer/Hyperspatial.svg",
        price: 12.99,
        bulkPrice: 23.99,
        bundleQuantity: 2,
        ABV: 7.8,
        size: 375,
      },
      {
        name: "Shizzert",
        rating: 4.12,
        ratingCount: "1xx",
        untappdUrl: "https://untappd.com/b/one-drop-brewing-co-shizzert/6057919",
        imageUrl: "assets/dark beer/Shizzert.svg",
        price: 17.99,
        bulkPrice: 31.99,
        bundleQuantity: 2,
        ABV: 9.8,
        size: 440,
      },
      {
        name: "Persian Princess",
        rating: 4.29,
        ratingCount: "4xx",
        untappdUrl: "https://untappd.com/b/one-drop-brewing-co-shizzert/6057919",
        imageUrl: "assets/dark beer/Persian Princess.svg",
        price: 19.99,
        bulkPrice: 35.99,
        bundleQuantity: 2,
        ABV: 13,
        size: 375,
      },
      {
        name: "Terramisu",
        rating: 4.4,
        ratingCount: "xx",
        untappdUrl: "https://untappd.com/b/bacchus-brewing-co-terramisu/3293391",
        imageUrl: "assets/dark beer/Terramisu.svg",
        price: 19.99,
        bulkPrice: 35.99,
        bundleQuantity: 2,
        ABV: 13.2,
        size: 375,
      }

  ],
  sourBeers: [
      {
        name: "Pickle Beer",
        rating: 3.63,
        ratingCount: "3.8k",
        untappdUrl: "https://untappd.com/b/garage-project-pickle-beer/4004935",
        imageUrl: "assets/Sour beer/Pickle Beer.svg",
        price: 5.99,
        bulkPrice: 20.99,
        bundleQuantity: 4,
        ABV: 4.3,
        size: 330,
      },
      {
        name: "Rainbow Sher...",
        rating: 3.7,
        ratingCount: "7.6k",
        untappdUrl: "https://untappd.com/b/gweilo-beer-rainbow-sherbet-sour-aus-6/3850646",
        imageUrl: "assets/Sour beer/Rainbow Sherbet.svg",
        price: 6.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 6,
        size: 375,
      },
      {
        name: "Apricot Sundae",
        rating: 3.62,
        ratingCount: "1xx",
        untappdUrl: "https://untappd.com/b/gweilo-beer-apricot-sundae-sour/4764377",
        imageUrl: "assets/Sour beer/Apricot Sundae.svg",
        price: 9.99,
        bulkPrice: 17.99,
        bundleQuantity: 2,
        ABV: 4.4,
        size: 440,
      },
      {
        name: "We Jammin'",
        rating: 4.29,
        ratingCount: "1.3k",
        untappdUrl: "https://untappd.com/b/one-drop-brewing-co-we-jammin-double-fruited-sour/4548672",
        imageUrl: "assets/Sour beer/We Jammin'.svg",
        price: 11.99,
        bulkPrice: 21.99,
        bundleQuantity: 2,
        ABV: 6.2,
        size: 375,
      },
      {
        name: "Bear Hug",
        rating: 3.89,
        ratingCount: "1xx",
        untappdUrl: "https://untappd.com/b/slow-lane-brewing-bear-hug/4827282",
        imageUrl: "assets/Sour beer/Bear Hug.svg",
        price: 11.99,
        bulkPrice: 20.99,
        bundleQuantity: 2,
        ABV: 6.5,
        size: 375,
      },
      {
        name: "Outback Sky",
        rating: 3.83,
        ratingCount: "2xx",
        untappdUrl: "https://untappd.com/b/slow-lane-brewing-outback-sky/4300712",
        imageUrl: "assets/Sour beer/Outback Sky.svg",
        price: 11.99,
        bulkPrice: 20.99,
        bundleQuantity: 2,
        ABV: 6,
        size: 375,
      },
      {
        name: "Swing Low",
        rating: 4.23,
        ratingCount: "3xx",
        untappdUrl: "https://untappd.com/b/one-drop-brewing-co-swing-low/5749490",
        imageUrl: "assets/Sour beer/Swing Low.svg",
        price: 14.99,
        bulkPrice: 25.99,
        bundleQuantity: 2,
        ABV: 5.5,
        size: 440,
      },
      {
        name: "All The Things",
        rating: 3.93,
        ratingCount: "2xx",
        untappdUrl: "https://untappd.com/b/garage-project-all-the-things/5755511",
        imageUrl: "assets/Sour beer/All The Things.svg",
        price: 14.99,
        bulkPrice: 25.99,
        bundleQuantity: 2,
        ABV: 9.3,
        size: 440,
      },
      {
        name: "Kilowatt",
        rating: 4.3,
        ratingCount: "3xx",
        untappdUrl: "https://untappd.com/b/one-drop-brewing-co-kilowatt/6005553",
        imageUrl: "assets/Sour beer/Kilowatt.svg",
        price: 15.99,
        bulkPrice: 27.99,
        bundleQuantity: 2,
        ABV: 6.8,
        size: 440,
      },
      {
        name: "Think Again",
        rating: 4.28,
        ratingCount: "1xx",
        untappdUrl: "https://untappd.com/b/one-drop-brewing-co-think-again/6040796",
        imageUrl: "assets/Sour beer/Think Again.svg",
        price: 15.99,
        bulkPrice: 27.99,
        bundleQuantity: 2,
        ABV: 6.1,
        size: 440,
      }


  ],
  paleAles: [
      {
        name: "Cooper Original",
        rating: 3.22,
        ratingCount: "70k",
        untappdUrl: "https://untappd.com/b/coopers-original-pale-ale/7884",
        imageUrl: "assets/Pale Ale/Cooper Original.svg",
        price: 3.49,
        bulkPrice: 18.99,
        bundleQuantity: 6,
        ABV: 4.5,
        size: 375,
      },
      {
        name: "Newtowner",
        rating: 3.52,
        ratingCount: "17k",
        untappdUrl: "https://untappd.com/b/young-henrys-newtowner/273570",
        imageUrl: "assets/Pale Ale/Newtowner.svg",
        price: 3.99,
        bulkPrice: 19.99,
        bundleQuantity: 6,
        ABV: 4.8,
        size: 375,
      },
      {
        name: "4 Pines Pale Ale",
        rating: 3.58,
        ratingCount: "21k",
        untappdUrl: "https://untappd.com/b/4-pines-brewing-company-pale-ale/16407",
        imageUrl: "assets/Pale Ale/4 Pines Pale Ale.svg",
        price: 4.49,
        bulkPrice: 15.99,
        bundleQuantity: 4,
        ABV: 5.1,
        size: 375,
      },
      {
        name: "South Coast",
        rating: 3.5,
        ratingCount: "8k",
        untappdUrl: "https://untappd.com/b/pirate-life-brewing-south-coast-pale-ale/3747651",
        imageUrl: "assets/Pale Ale/South Coast.svg",
        price: 4.49,
        bulkPrice: 13.99,
        bundleQuantity: 4,
        ABV: 4.4,
        size: 355,
      },
      {
        name: "Kaiju Krush",
        rating: 3.66,
        ratingCount: "18k",
        untappdUrl: "https://untappd.com/b/kaiju-beer-kaiju-krush/1843438",
        imageUrl: "assets/Pale Ale/Kaiju Krush.svg",
        price: 4.99,
        bulkPrice: 24.99,
        bundleQuantity: 6,
        ABV: 4.7,
        size: 375,
      },
      {
        name: "California Pale...",
        rating: 3.63,
        ratingCount: "2k",
        untappdUrl: "https://untappd.com/b/pirate-life-brewing-california-pale-ale/4443280",
        imageUrl: "assets/Pale Ale/California Pale Ale.svg",
        price: 4.99,
        bulkPrice: 17.99,
        bundleQuantity: 4,
        ABV: 5.8,
        size: 355,
      },
      {
        name: "Little Creatures",
        rating: 3.57,
        ratingCount: "52k",
        untappdUrl: "https://untappd.com/b/little-creatures-brewing-pale-ale/8261",
        imageUrl: "assets/Pale Ale/Little Creatures.svg",
        price: 4.99,
        bulkPrice: 14.99,
        bundleQuantity: 4,
        ABV: 5.2,
        size: 375,
      },
      {
        name: "Gipps st",
        rating: 3.63,
        ratingCount: "6k",
        untappdUrl: "https://untappd.com/b/stomping-ground-brewing-co-gipps-st/1507443",
        imageUrl: "assets/Pale Ale/Gipps st.svg",
        price: 4.99,
        bulkPrice: 24.99,
        bundleQuantity: 6,
        ABV: 5.2,
        size: 355,
      },
      {
        name: "Cloudy Pale Ale",
        rating: 3.54,
        ratingCount: "7xx",
        untappdUrl: "https://untappd.com/b/stone-and-wood-cloudy-pale-ale/5459568",
        imageUrl: "assets/Pale Ale/Cloudy Pale Ale.svg",
        price: 5.49,
        bulkPrice: 17.99,
        bundleQuantity: 4,
        ABV: 5,
        size: 375,
      },
      {
        name: "The Heart",
        rating: 3.6,
        ratingCount: "12k",
        untappdUrl: "https://untappd.com/b/hop-nation-brewing-co-the-heart/2114779",
        imageUrl: "assets/Pale Ale/The Heart.svg",
        price: 5.99,
        bulkPrice: 21.99,
        bundleQuantity: 4,
        ABV: 4.6,
        size: 355,
      },
      {
        name: "Sierra Nevada",
        rating: 3.62,
        ratingCount: "500k",
        untappdUrl: "https://untappd.com/b/sierra-nevada-brewing-co-pale-ale/6284",
        imageUrl: "assets/Pale Ale/Sierra Nevada.svg",
        price: 5.99,
        bulkPrice: 19.99,
        bundleQuantity: 4,
        ABV: 5,
        size: 375,
      },
      {
        name: "Fox Friday ",
        rating: 3.74,
        ratingCount: "1k",
        untappdUrl: "https://untappd.com/b/fox-friday-craft-brewery-pale-ale/4847564",
        imageUrl: "assets/Pale Ale/Fox Friday Pale Ale.svg",
        price: 6.49,
        bulkPrice: 22.99,
        bundleQuantity: 4,
        ABV: 5,
        size: 375,
      },
      {
        name: "Status Quo",
        rating: 3.93,
        ratingCount: "8k",
        untappdUrl: "https://untappd.com/b/mountain-culture-beer-co-status-quo/3554194",
        imageUrl: "assets/Pale Ale/Status Quo.svg",
        price: 6.49,
        bulkPrice: 21.99,
        bundleQuantity: 4,
        ABV: 5.2,
        size: 355,
      },
      {
        name: "Range Disco",
        rating: 3.85,
        ratingCount: "1.8k",
        untappdUrl: "https://untappd.com/b/range-brewing-disco/5088619",
        imageUrl: "assets/Pale Ale/Range Disco.svg",
        price: 6.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 5.2,
        size: 330,
      },
      {
        name: "Conditioned",
        rating: 3.79,
        ratingCount: "4xx",
        untappdUrl: "https://untappd.com/b/slow-lane-brewing-conditioned/5433235",
        imageUrl: "assets/Pale Ale/Conditioned.svg",
        price: 6.99,
        bulkPrice: 23.99,
        bundleQuantity: 4,
        ABV: 5.4,
        size: 375,
      },
      {
        name: "Core Workout",
        rating: 3.86,
        ratingCount: "xx",
        untappdUrl: "https://untappd.com/b/hawkers-beer-core-workout-pale-ale/6066974",
        imageUrl: "assets/Pale Ale/Core Workout Pale Ale.svg",
        price: 11.99,
        bulkPrice: 29.99,
        bundleQuantity: 3,
        ABV: 4.8,
        size: 440,
      }
  ],
  IPA: [
    {
        name: "Voodoo Ranger",
        rating: 3.6,
        ratingCount: "1.4k",
        untappdUrl: "https://untappd.com/b/new-belgium-brewing-company-voodoo-ranger-hazy-ipa/4000288",
        imageUrl: "assets/IPA/Voodoo Ranger.svg",
        price: 4.99,
        bulkPrice: 16.99,
        bundleQuantity: 4,
        ABV: 5,
        size: 375,
      },
      {
        name: "Crank Shaft",
        rating: 3.86,
        ratingCount: "13k",
        untappdUrl: "https://untappd.com/b/bentspoke-brewing-co-crankshaft/704499",
        imageUrl: "assets/IPA/Crank Shaft.svg",
        price: 5.99,
        bulkPrice: 19.99,
        bundleQuantity: 4,
        ABV: 5.8,
        size: 375,
      },
      {
        name: "Hop Stomper",
        rating: 3.73,
        ratingCount: "5k",
        untappdUrl: "https://untappd.com/b/stomping-ground-brewing-co-hop-stomper/2376806",
        imageUrl: "assets/IPA/Hop Stomper.svg",
        price: 5.99,
        bulkPrice: 29.99,
        bundleQuantity: 6,
        ABV: 6,
        size: 355,
      },
      {
        name: "Balter Hazy IPA",
        rating: 3.95,
        ratingCount: "10k",
        untappdUrl: "https://untappd.com/b/balter-brewing-company-hazy-ipa/3077298",
        imageUrl: "assets/IPA/Balter Hazy IPA.svg",
        price: 5.99,
        bulkPrice: 19.99,
        bundleQuantity: 4,
        ABV: 6,
        size: 375,
      },
      {
        name: "Jungle Juice",
        rating: 3.81,
        ratingCount: "5.5k",
        untappdUrl: "https://untappd.com/b/dainton-beer-jungle-juice/3576518",
        imageUrl: "assets/IPA/Jungle Juice.svg",
        price: 6.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 6.5,
        size: 375,
      },
      {
        name: "The Chop",
        rating: 3.87,
        ratingCount: "6.7k",
        untappdUrl: "https://untappd.com/b/hop-nation-brewing-co-the-chop/1744654",
        imageUrl: "assets/IPA/The Chop.svg",
        price: 6.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 6,
        size: 355,
      },
      {
        name: "J Juice",
        rating: 3.93,
        ratingCount: "10.6k",
        untappdUrl: "https://untappd.com/b/hop-nation-brewing-co-j-juice/2071510",
        imageUrl: "assets/IPA/J Juice.svg",
        price: 6.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 7.1,
        size: 355,
      },
      {
        name: "Hawkesbury IPA",
        rating: 3.56,
        ratingCount: "2xx",
        untappdUrl: "https://untappd.com/b/hawkesbury-brewing-company-ipa/5129746",
        imageUrl: "assets/IPA/Hawkesbury IPA.svg",
        price: 6.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 6.3,
        size: 375,
      },
      {
        name: "Cult IPA",
        rating: 3.97,
        ratingCount: "6k",
        untappdUrl: "https://untappd.com/b/mountain-culture-beer-co-cult-ipa/3484719",
        imageUrl: "assets/IPA/Cult IPA.svg",
        price: 7.99,
        bulkPrice: 24.99,
        bundleQuantity: 4,
        ABV: 6.2,
        size: 355,
      },
      {
        name: "Fox Friday Hazy...",
        rating: 3.88,
        ratingCount: "1.9k",
        untappdUrl: "https://untappd.com/b/fox-friday-craft-brewery-hazy-ipa/4898708",
        imageUrl: "assets/IPA/Fox Friday Hazy IPA.svg",
        price: 7.99,
        bulkPrice: 27.99,
        bundleQuantity: 4,
        ABV: 6,
        size: 375,
      },
      {
        name: "Supersaturated",
        rating: 3.93,
        ratingCount: "5xx",
        untappdUrl: "https://untappd.com/b/slow-lane-brewing-supersaturated/5484870",
        imageUrl: "assets/IPA/Supersaturated.svg",
        price: 7.99,
        bulkPrice: 27.99,
        bundleQuantity: 4,
        ABV: 6.7,
        size: 375,
      },
      {
        name: "Aftermath",
        rating: 3.91,
        ratingCount: "7k",
        untappdUrl: "https://untappd.com/b/kaiju-beer-aftermath/458300",
        imageUrl: "assets/IPA/Aftermath.svg",
        price: 7.99,
        bulkPrice: 27.99,
        bundleQuantity: 4,
        ABV: 9.1,
        size: 375,
      },
      {
        name: "Core Workout",
        rating: 3.85,
        ratingCount: "1xx",
        untappdUrl: "https://untappd.com/b/hawkers-beer-core-workout-ipa/6066979",
        imageUrl: "assets/IPA/Core Workout IPA.svg",
        price: 11.99,
        bulkPrice: 29.99,
        bundleQuantity: 3,
        ABV: 6,
        size: 440,
      },
      {
        name: "Hyperdelic",
        rating: 4.15,
        ratingCount: "xx",
        untappdUrl: "https://untappd.com/b/bacchus-brewing-co-hyperdelic/6035227",
        imageUrl: "assets/IPA/Hyperdelic.svg",
        price: 12.99,
        bulkPrice: 23.99,
        bundleQuantity: 2,
        ABV: 7.4,
        size: 375,
      },
      {
        name: "High Tea",
        rating: 3.83,
        ratingCount: "2xx",
        untappdUrl: "https://untappd.com/b/bacchus-brewing-co-high-tea-ipa/2610430",
        imageUrl: "assets/IPA/High Tea.svg",
        price: 12.99,
        bulkPrice: 23.99,
        bundleQuantity: 2,
        ABV: 6.7,
        size: 375,
      },
      {
        name: "4 Seasons: Su...",
        rating: 4.21,
        ratingCount: "1xx",
        untappdUrl: "https://untappd.com/b/hawkers-beer-four-seasons-summer-2024/6081946",
        imageUrl: "assets/IPA/Summer.svg",
        price: 15.99,
        bulkPrice: 27.99,
        bundleQuantity: 2,
        ABV: 10,
        size: 440,
      }
  ],
  Ale: [
    {
        name: "Classic Pale",
        rating: 4.15,
        ratingCount: 324,
        untappdUrl: "https://untappd.com/example-pale",
        imageUrl: "assets/images/pale-ale.svg",
        price: 9.99,
        bulkPrice: 8.99
    }
  ],
  XPA: [
  {
      name: "Classic Pale",
      rating: 4.15,
      ratingCount: 324,
      untappdUrl: "https://untappd.com/example-pale",
      imageUrl: "assets/images/pale-ale.svg",
      price: 9.99,
      bulkPrice: 8.99
  }
  ],
  Zero: [
    {
      name: "Yeah Nah Pale Ale",
      rating: 2.87,
      ratingCount: "xx",
      untappdUrl: "https://untappd.com/b/yeah-nah-pale-ale/5881118",
      imageUrl: "assets/Zero/Yeah Nah Pale Ale.svg",
      price: 3.49,
      bulkPrice: 11.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 375,
    },
    {
      name: "Yeah Nah XPA",
      rating: 2.8,
      ratingCount: "xx",
      untappdUrl: "https://untappd.com/b/yeah-nah-xpa/5881120",
      imageUrl: "assets/Zero/Yeah Nah XPA.svg",
      price: 3.49,
      bulkPrice: 11.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 375,
    },
    {
      name: "Half Day Hazy",
      rating: 3.42,
      ratingCount: "7xx",
      untappdUrl: "https://untappd.com/b/heaps-normal-half-day-hazy/5142507",
      imageUrl: "assets/Zero/Half Day Hazy.svg",
      price: 3.99,
      bulkPrice: 11.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 375,
    },
    {
      name: "Another Lager",
      rating: 2.82,
      ratingCount: "7xx",
      untappdUrl: "https://untappd.com/b/heaps-normal-another-lager/4677573",
      imageUrl: "assets/Zero/Another Lager.svg",
      price: 3.99,
      bulkPrice: 11.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 375,
    },
    {
      name: "Quiet XPA",
      rating: 3.27,
      ratingCount: "3k",
      untappdUrl: "https://untappd.com/b/heaps-normal-quiet-xpa/3796765",
      imageUrl: "assets/Zero/Quiet XPA.svg",
      price: 3.99,
      bulkPrice: 11.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 375,
    },
    {
      name: "Third IPA",
      rating: 3.2,
      ratingCount: "370",
      untappdUrl: "https://untappd.com/b/heaps-normal-third-ipa/6024809",
      imageUrl: "assets/Zero/Third IPA.svg",
      price: 4.49,
      bulkPrice: 14.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 375,
    },
    {
      name: "Deeds Zero",
      rating: 3.34,
      ratingCount: "1xx",
      untappdUrl: "https://untappd.com/b/deeds-brewing-deeds-zero/4715502",
      imageUrl: "assets/Zero/Deeds Zero.svg",
      price: 4.49,
      bulkPrice: 15.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 375,
    },
    {
      name: "Tiny But Mighty",
      rating: 3.46,
      ratingCount: "1.4k",
      untappdUrl: "https://untappd.com/b/garage-project-tiny-but-mighty/4485065",
      imageUrl: "assets/Zero/Tiny.svg",
      price: 4.49,
      bulkPrice: 14.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 330,
    },
    {
      name: "Zero Smash",
      rating: 3.6,
      ratingCount: "xx",
      untappdUrl: "https://untappd.com/b/stomping-ground-brewing-co-zero-smash/5250637",
      imageUrl: "assets/Zero/Zero Smash.svg",
      price: 4.99,
      bulkPrice: 16.99,
      bundleQuantity: 4,
      ABV: 0.5,
      size: 355,
    },
  ],
  Specialty: [
    {
        name: "Classic Pale",
        rating: 4.15,
        ratingCount: 324,
        untappdUrl: "https://untappd.com/example-pale",
        imageUrl: "assets/images/pale-ale.svg",
        price: 9.99,
        bulkPrice: 8.99
    }
  ],
  Imported: [
    {
      name: "Terra",
      rating: 3.03,
      ratingCount: "16k",
      untappdUrl: "https://untappd.com/b/hitejinro-terra/3144712",
      imageUrl: "assets/Imported/Terra.svg",
      price: 3.49,
      bulkPrice: 16.99,
      bundleQuantity: 6,
      ABV: 4.6,
      size: 355,
    },
    {
      name: "Cass",
      rating: 2.81,
      ratingCount: "60k",
      untappdUrl: "https://untappd.com/b/oriental-brewery-cass-fresh/3700",
      imageUrl: "assets/Imported/Cass.svg",
      price: 3.49,
      bulkPrice: 17.99,
      bundleQuantity: 6,
      ABV: 4.5,
      size: 355,
    },
    {
      name: "Kirin Ichiban",
      rating: 3.15,
      ratingCount: "375k",
      untappdUrl: "https://untappd.com/b/kirin-brewery-company-ichiban-ichiban-shibori/4667",
      imageUrl: "assets/Imported/Kirin Ichiban.svg",
      price: 3.49,
      bulkPrice: 17.99,
      bundleQuantity: 6,
      ABV: 5,
      size: 330,
    },
    {
      name: "Tsing Tao",
      rating: 2.89,
      ratingCount: "311k",
      untappdUrl: "https://untappd.com/b/tsingtao-brewery-tsingtao/6601",
      imageUrl: "assets/Imported/Tsing Tao.svg",
      price: 3.69,
      bulkPrice: 18.99,
      bundleQuantity: 6,
      ABV: 4.7,
      size: 330,
    },
    {
      name: "Kingfisher",
      rating: 2.98,
      ratingCount: "158k",
      untappdUrl: "https://untappd.com/b/united-breweries-kingfisher-premium-lager/17377",
      imageUrl: "assets/Imported/Kingfisher.svg",
      price: 3.79,
      bulkPrice: 19.99,
      bundleQuantity: 6,
      ABV: 5,
      size: 330,
    },
    {
      name: "Saigon 333",
      rating: 2.75,
      ratingCount: "20k",
      untappdUrl: "https://untappd.com/b/sabeco-333-premium-export/24194",
      imageUrl: "assets/Imported/333.svg",
      price: 3.99,
      bulkPrice: 19.99,
      bundleQuantity: 6,
      ABV: 5.3,
      size: 355,
    },
    {
      name: "Saigon Special",
      rating: 2.9,
      ratingCount: "32k",
      untappdUrl: "https://untappd.com/b/sabeco-saigon-special/17357",
      imageUrl: "assets/Imported/Saigon bt.svg",
      price: 3.99,
      bulkPrice: 20.99,
      bundleQuantity: 6,
      ABV: 4.9,
      size: 330,
    },
    {
      name: "Chang Beer",
      rating: 2.93,
      ratingCount: "150k",
      untappdUrl: "https://untappd.com/b/thai-beverage-plc-chang-classic/83409",
      imageUrl: "assets/Imported/Chang.svg",
      price: 3.99,
      bulkPrice: 20.99,
      bundleQuantity: 6,
      ABV: 5,
      size: 330,
    },
    {
      name: "Singha Beer",
      rating: 3.06,
      ratingCount: "275k",
      untappdUrl: "https://untappd.com/b/boon-rawd-brewery-singha/6344",
      imageUrl: "assets/Imported/Singha.svg",
      price: 3.99,
      bulkPrice: 20.99,
      bundleQuantity: 6,
      ABV: 5,
      size: 330,
    },
    {
      name: "Beer Lao",
      rating: 3.03,
      ratingCount: "38k",
      untappdUrl: "https://untappd.com/b/lao-brewery-beerlao-lager/65020",
      imageUrl: "assets/Imported/Lao.svg",
      price: 3.99,
      bulkPrice: 20.99,
      bundleQuantity: 6,
      ABV: 5,
      size: 330,
    },
    {
      name: "Beer Lao Gold",
      rating: 3.05,
      ratingCount: "4k",
      untappdUrl: "https://untappd.com/b/lao-brewery-beerlao-gold/355292",
      imageUrl: "assets/Imported/Lao Gold.svg",
      price: 3.99,
      bulkPrice: 20.99,
      bundleQuantity: 6,
      ABV: 5,
      size: 330,
    },
    {
      name: "Angkor Beer",
      rating: 2.83,
      ratingCount: "15k",
      untappdUrl: "https://untappd.com/b/cambrew-angkor-beer/7014",
      imageUrl: "assets/Imported/Angkor.svg",
      price: 3.99,
      bulkPrice: 19.99,
      bundleQuantity: 6,
      ABV: 5,
      size: 330,
    },
    {
      name: "Hanoi premium",
      rating: 2.91,
      ratingCount: "18k",
      untappdUrl: "https://untappd.com/b/habeco-hanoi-premium-beer/17356",
      imageUrl: "assets/Imported/Hanoi bt.svg",
      price: 4.49,
      bulkPrice: 21.99,
      bundleQuantity: 6,
      ABV: 4.9,
      size: 330,
    },
    {
      name: "Hanoi",
      rating: 2.8,
      ratingCount: "18k",
      untappdUrl: "https://untappd.com/b/habeco-bia-ha-noi/17374",
      imageUrl: "assets/Imported/Hanoi can.svg",
      price: 4.49,
      bulkPrice: 21.99,
      bundleQuantity: 6,
      ABV: 4.6,
      size: 330,
    },
    {
      name: "Angkor Stout",
      rating: 3.21,
      ratingCount: "2k",
      untappdUrl: "https://untappd.com/b/cambrew-angkor-extra-stout/21282",
      imageUrl: "assets/Imported/Angkor Stout.svg",
      price: 4.49,
      bulkPrice: 23.99,
      bundleQuantity: 6,
      ABV: 8,
      size: 330,
    },
    {
      name: "Tsing Tao",
      rating: 2.89,
      ratingCount: "311k",
      untappdUrl: "https://untappd.com/b/tsingtao-brewery-tsingtao/6601",
      imageUrl: "assets/Imported/Tsing Tao 640.svg",
      price: 6.49,
      bulkPrice: 16.99,
      bundleQuantity: 3,
      ABV: 4.7,
      size: 640,
    },
    {
      name: "Kingfisher Strong",
      rating: 2.93,
      ratingCount: "9k",
      untappdUrl: "https://untappd.com/b/united-breweries-kingfisher-strong/35856",
      imageUrl: "assets//Imported/Kingfisher Strong.svg",
      price: 6.99,
      bulkPrice: 35.99,
      bundleQuantity: 6,
      ABV: 8,
      size: 500,
    },
    {
      name: "Hefeweissbier Dunkel",
      rating: 3.76,
      ratingCount: "103k",
      untappdUrl: "https://untappd.com/b/bayerische-staatsbrauerei-weihenstephan-weihenstephaner-hefeweissbier-dunkel/6273",
      imageUrl: "assets/Imported/Dunkel.svg",
      price: 7.99,
      bulkPrice: 20.99,
      bundleQuantity: 3,
      ABV: 5.3,
      size: 500,
    },
    {
      name: "Traditional Dunkel",
      rating: 3.58,
      ratingCount: "7.9k",
      untappdUrl: "https://untappd.com/b/bayerische-staatsbrauerei-weihenstephan-weihenstephaner-tradition/32551",
      imageUrl: "assets/Imported/Traditional Dunkel.svg",
      price: 7.99,
      bulkPrice: 20.99,
      bundleQuantity: 3,
      ABV: 5.2,
      size: 500,
    },
    {
      name: "Weihenstephaner Original",
      rating: 3.61,
      ratingCount: "90k",
      untappdUrl: "https://untappd.com/b/bayerische-staatsbrauerei-weihenstephan-weihenstephaner-original/2716",
      imageUrl: "assets/Imported/Weihenstephaner Original.svg",
      price: 7.99,
      bulkPrice: 20.99,
      bundleQuantity: 3,
      ABV: 5.1,
      size: 500,
    },
    {
      name: "Lion Lager",
      rating: 3.05,
      ratingCount: "20k",
      untappdUrl: "https://untappd.com/b/lion-brewery-ceylon-lion-lager/37408",
      imageUrl: "assets/Imported/Lion Lager.svg",
      price: 8.49,
      bulkPrice: 21.99,
      bundleQuantity: 3,
      ABV: 4.8,
      size: 625,
    },
    {
      name: "Lion Strong",
      rating: 2.85,
      ratingCount: "4.7k",
      untappdUrl: "https://untappd.com/b/lion-brewery-ceylon-lion-strong/295352",
      imageUrl: "assets/Imported/Lion Strong.svg",
      price: 11.99,
      bulkPrice: 31.99,
      bundleQuantity: 3,
      ABV: 8.8,
      size: 625,
    },
    {
      name: "Lion Stout",
      rating: 3.59,
      ratingCount: "38k",
      untappdUrl: "https://untappd.com/b/lion-brewery-ceylon-lion-stout/2001",
      imageUrl: "assets/Imported/Lion Stout.svg",
      price: 11.99,
      bulkPrice: 31.99,
      bundleQuantity: 3,
      ABV: 8.8,
      size: 625,
    },
  ],
  Pilsner: [
  {
      name: "Classic Pale",
      rating: 4.15,
      ratingCount: 324,
      untappdUrl: "https://untappd.com/example-pale",
      imageUrl: "assets/images/pale-ale.svg",
      price: 9.99,
      bulkPrice: 8.99
  }
  ],
};

// Function to generate HTML using accumulator pattern
function generateBeerShelfHTML(beersArray) {
  let shelfHTML = '';
  
  beersArray.forEach(beer => {
      // Calculate rating width as a percentage
      const ratingWidth = (beer.rating / 5) * 100;
      const Saving =Math.floor(((beer.price *beer.bundleQuantity)-beer.bulkPrice)/(beer.price *beer.bundleQuantity)*100);
      
      shelfHTML += `
          <div class="shop-product-card">
              <div>
                  <a href="${beer.untappdUrl}" class="shop-rating" target="_blank">
                          <i class="fas fa-star star"></i> <!-- Solid Star -->
${beer.rating} <span class="quantity">(${beer.ratingCount})</span>
                  </a>
              </div>
              <div class="rating-bar">
                  <div class="rating-fill" style="width: ${ratingWidth}%;"></div>
              </div>
              <div class="shop-name">${beer.name}</div>
              <div class='shop-spec'>
              ${beer.ABV}%<span class='quantity'> ABV, </span>
              ${beer.size}<span class='quantity'> ml </span>
              </div>
              <a href="${beer.untappdUrl}" target="_blank">
                <img src="${beer.imageUrl}" alt="${beer.name}" class="shop-product-image">
              </a>
                <div class="shop-price">
                    <span class='shop-dollar'>$ </span>${Math.floor(beer.price)}
                    <span class='shop-dollar'>${(beer.price % 1).toFixed(2).slice(2)}</span>
                    <span class='quantity'>EACH</span>
                </div>
                <div class="shop-bulkprice">
                    <span>${beer.bundleQuantity}</span>
                    <span class='quantity'> FOR</span>
                    <span class='shop-dollar'>$ </span>${Math.floor(beer.bulkPrice)}
                    <span class='shop-dollar'>${(beer.bulkPrice % 1).toFixed(2).slice(2)} </span>
                  <div class='saving-text'> 
                  <span class='quantity'>SAVE</span>
                  <span> ${Saving}%</span>
                  </div>
                </div>
          </div>
      `;
  });
  
  return shelfHTML;
}

// Function to initialize all beer shelves
function initializeBeerShelves() {
  // Dark Beers
  const darkBeersHTML = generateBeerShelfHTML(beers.darkBeers);
  document.querySelector('.js-load-dark-beer').innerHTML = darkBeersHTML;
  
  // Imported
  const ImportedHTML = generateBeerShelfHTML(beers.Imported);
  document.querySelector('.js-load-Imported').innerHTML = ImportedHTML;
  
  // IPA
  const IPAHTML = generateBeerShelfHTML(beers.IPA);
  document.querySelector('.js-load-IPA').innerHTML = IPAHTML;
  
  // Pale Ales
  const paleAlesHTML = generateBeerShelfHTML(beers.paleAles);
  document.querySelector('.js-load-pale-ale').innerHTML = paleAlesHTML;
  
  // Sour Beers
  const sourBeersHTML = generateBeerShelfHTML(beers.sourBeers);
  document.querySelector('.js-load-sour-beer').innerHTML = sourBeersHTML;
  // Zero
  const ZeroHTML = generateBeerShelfHTML(beers.Zero);
  document.querySelector('.js-load-Zero').innerHTML = ZeroHTML;

  

  // ALe
  const AleHTML = generateBeerShelfHTML(beers.Ale);
  document.querySelector('.js-load-Ale').innerHTML = AleHTML;
  
  // XPA
  const XPAHTML = generateBeerShelfHTML(beers.XPA);
  document.querySelector('.js-load-XPA').innerHTML = XPAHTML;
  
  
  // Specialty
  const SpecialtyHTML = generateBeerShelfHTML(beers.Specialty);
  document.querySelector('.js-load-Specialty').innerHTML = SpecialtyHTML;
  
  // Pilsner
  const PilsnerHTML = generateBeerShelfHTML(beers.Pilsner);
  document.querySelector('.js-load-Pilsner').innerHTML = PilsnerHTML;

}


// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', initializeBeerShelves);
